name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '23'

      # Step 3: Get list of modified files
      - name: Get list of modified files
        id: files
        run: |
          echo "Modified files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
          cat modified_files.txt
          echo "::set-output name=files::$(cat modified_files.txt)"

      # Step 4: Run tests for modified files
      - name: Run tests for modified files
        run: |
          modified_files="${{ steps.files.outputs.files }}"
          echo "Modified fi
